<?php
/**
 * Created by PhpStorm.
 * User: mageuser
 * Date: 1/17/17
 * Time: 10:03 AM
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form"><?php echo $this->getLogFileName() ?></h4>
        </div>
        <div id="log_details_fieldset" class="log-details">
            <pre style="white-space: pre-wrap;"><?php echo $this->getLogContents(); ?></pre>
        </div>
    </div>
</div>
