<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Relatedproducts
 * @version    1.4.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if($this->getEnabled() && count($this->getRelatedProductsCollection())): ?>
    <div class="section-title"><h3>Others Also Purchased</h3></div>
        <div class="product-related-accessories">
            <div class="category-products">
                <ul class="products-grid">
                    <?php foreach($this->getRelatedProductsCollection() as $_item): ?>
                        <?php /** @var Mage_Catalog_Model_Product $_item */ ?>
                        <li class="item">
                            <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>">
                                <div class="category-products-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'image')->resize(260) ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></div>
                                <div class="product-info clearfix">
                                    <div class="product-east">
                                        <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                                        <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>'); return false;">
                                            <span><span>Add to Cart</span></span>
                                        </button>
                                    </div>
                                    <div class="product-west">
                                        <h2 class="product-name"><?php echo $this->escapeHtml($_item->getName()) ?></h2>
                                        <div class="product-category"><?php echo Mage::helper('shelterlogic_templates')->getCategoryName($_item) ?></div>
                                    </div>
                                </div>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
<?php endif ?>