<?php
    $_parentBlock = $this->getParentBlock();
    $_collection = $this->getCollection();
?>
<?php if (count($_collection)): ?>
<li>
    <h3><span><?php echo $this->getTitle() ?></span></h3>
    <ul>
        <?php foreach ($_collection as $_product): ?>
        <?php
            /** @var Mage_Catalog_Model_Product $_product */
            $_product->unsUrl();
            $_product->unsRequestPath();
            $_product->setDoNotUseCategoryId(true);
            ?>
        <li>
            <a class="clearfix" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_parentBlock->escapeHtml($_product->getName()) ?>">
                <div class="product-west">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(75) ?>" alt="<?php echo $_parentBlock->escapeHtml($_product->getName()) ?>" />
                </div>
                <div class="product-east">
                    <h4 class="product-name"><?php echo $_parentBlock->escapeHtml($_product->getName()) ?></h4>
                    <?php echo $_parentBlock->getPriceHtml($_product) ?>
                </div>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
</li>
<?php endif; ?>