<?php 
/**
 * MagPassion_Advancedmenu extension
 * 
 * @category   	MagPassion
 * @package		MagPassion_Advancedmenu
 * @copyright  	Copyright (c) 2013 by MagPassion (http://magpassion.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * Menu Group view template
 *
 * @category	MagPassion
 * @package		MagPassion_Advancedmenu
 * @author MagPassion.com
 */
?>
<?php $_menugroup = $this->getMenuGroup();?>
<?php if ($_menugroup) : ?>
	<?php $type = $_menugroup->getType(); ?>
	
	<?php if ($type == 'mega'): ?>
		<script type="text/javascript">
/*
			document.observe("dom:loaded", function() {
				var navWidth = parseInt(jQuery('ul.magpassion-menu-mega').width());
				
				jQuery('ul.level1 > li').each(function(){
					var curr = jQuery(this);
					//$currWidth = current.width();
					
					var maxHeight = 0;
					var totalWidth = 0;
					jQuery(this).find('.magpassion-child-content').each(function(){
						if (jQuery(this).height() > maxHeight) maxHeight = jQuery(this).height();
						if (totalWidth + jQuery(this).width() > navWidth) {
							curr.css({width: totalWidth});
						}
						else totalWidth += (jQuery(this).width() + 1);
					});
*/
					/*jQuery(this).find('.magpassion-child-content').each(function(){
						if (jQuery(this).height() < maxHeight)
							jQuery(this).css({ height: maxHeight});
					}); */
/*
				});
				
				jQuery('ul.magpassion-menu-mega > li').hover(function() {
					var m = jQuery(this).find('ul.level1');
					if (m !== null && m.length > 0) {
						var mwidth = parseInt(m.width());
						if (mwidth + parseInt(m.position().left) >= navWidth) {					
							m.css({ left: (navWidth-mwidth) });
						}
					}
				},
				function() {
					jQuery(this).find('ul.level1').removeAttr("style");
				
				});

				
			});
*/
		</script>
	<?php else: ?>
		<script type="text/javascript">
			document.observe("dom:loaded", function() {
				mainNav("magpassion-menu-<?=$type?>", {"show_delay":"100","hide_delay":"100"});
			});
		</script>
	<?php endif; ?>
	
	<?php echo $this->drawMenu($_menugroup->getName(), $type ); ?>
<?php else: ?>
	<?php echo "<p>Cannot find menugroup with id = ". $this->menuId.'</p>'; ?>
<?php endif; ?>