<?php
$_product    = $this->getProduct();
$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
$_jsonConfig = $this->getJsonConfig();
$_renderers = $this->getChild('attr_renderers')->getSortedChildren();
$_super_att_index = 1;
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <dl>
    <?php foreach($_attributes as $_attribute): ?>
        <?php
        $_rendered = false;
        foreach ($_renderers as $_rendererName):
            $_renderer = $this->getChild('attr_renderers')->getChild($_rendererName);
            if (method_exists($_renderer, 'shouldRender') && $_renderer->shouldRender($_product, $_attribute, $_jsonConfig)):
                $_renderer->setProduct($_product);
                $_renderer->setAttributeObj($_attribute);
                echo $_renderer->toHtml();
                $_rendered = true;
                break;
            endif;
        endforeach;

        if (!$_rendered):
            $_configID = str_replace( ' ', '',$_attribute->getLabel() );
        ?>
        <dt></dt>
        <dd<?php if ($_attribute->decoratedIsLast){?> class="last"<?php }?>>
            <div class="input-box">
                <label for="attribute<?php echo $_attribute->getAttributeId() ?>" class="required visuallyHidden"><em>*</em><?php echo $_attribute->getLabel() ?></label>
                <select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" data-index="<?php echo $_super_att_index ?>" id="attribute<?php echo $_attribute->getAttributeId() ?>" class="configurable_<?php echo $_configID; ?> required-entry super-attribute-select">
                    <option><?php echo $_attribute->getLabel() ?></option>
                </select>
            </div>
        </dd>
        <?php $_super_att_index++; ?>
        <?php endif; ?>
    <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
		var aeProductId = <?php echo $_product->getId(); ?>;
		var priceFormat = <?php echo $this->helper('tax')->getPriceFormat($this->getStore()); ?>;
		var aeConfig = new aeProduct.Config(<?php echo $_jsonConfig ?>);
	</script>
    <?php echo $this->getChildHtml('after') ?>
<?php endif;?>
