<?php if ($this->getIsEnabled()):?>
<?php
$doShowContentJs = Mage::getStoreConfig('bazaarvoice/rr/do_show_content_js');
$seoContent = $this->getSEOContent();
?>
<div id="BVRRContainer">
    <?php echo $seoContent ?>
</div>
<script type="text/javascript">
  $BV.ui( 'rr', 'show_reviews', {
    doShowContent : function () {
      <?php echo $doShowContentJs ?>
      jQuery('.toggle-tabs li.current').removeClass('current');
      jQuery('.toggle-tabs li').eq(-2).addClass('current');
      jQuery('.collateral-tabs dt.current').removeClass('current');
      jQuery('#dt_tab_reviews').addClass('current');
      jQuery('.collateral-tabs dd.current').removeClass('current');
      jQuery('#dd_tab_reviews').addClass('current');

    }
  });    
</script>
<?php endif; ?>
