<?php


 function autoload_7d104799db9f3474a7613fa25a772746($class)
{
    $classes = array(
        'Visual\CustomerService\CustomerService' => __DIR__ .'/CustomerService.php',
        'Visual\CustomerService\SampleXML' => __DIR__ .'/SampleXML.php',
        'Visual\CustomerService\SampleXMLResponse' => __DIR__ .'/SampleXMLResponse.php',
        'Visual\CustomerService\CustomerData' => __DIR__ .'/CustomerData.php',
        'Visual\CustomerService\ArrayOfCustomer' => __DIR__ .'/ArrayOfCustomer.php',
        'Visual\CustomerService\Customer' => __DIR__ .'/Customer.php',
        'Visual\CustomerService\ExternalReference' => __DIR__ .'/ExternalReference.php',
        'Visual\CustomerService\ArrayOfReference' => __DIR__ .'/ArrayOfReference.php',
        'Visual\CustomerService\Reference' => __DIR__ .'/Reference.php',
        'Visual\CustomerService\CustomerSite' => __DIR__ .'/CustomerSite.php',
        'Visual\CustomerService\CustomerEntity' => __DIR__ .'/CustomerEntity.php',
        'Visual\CustomerService\CustomerAddress' => __DIR__ .'/CustomerAddress.php',
        'Visual\CustomerService\ArrayOfCustomerAddress' => __DIR__ .'/ArrayOfCustomerAddress.php',
        'Visual\CustomerService\ArrayOfCustomerEntity' => __DIR__ .'/ArrayOfCustomerEntity.php',
        'Visual\CustomerService\ArrayOfCustomerSite' => __DIR__ .'/ArrayOfCustomerSite.php',
        'Visual\CustomerService\ConfigureNextNumberGen' => __DIR__ .'/ConfigureNextNumberGen.php',
        'Visual\CustomerService\ConfigureNextNumberGenResponse' => __DIR__ .'/ConfigureNextNumberGenResponse.php',
        'Visual\CustomerService\GetShipViaCodes2' => __DIR__ .'/GetShipViaCodes2.php',
        'Visual\CustomerService\GetShipViaCodes2Response' => __DIR__ .'/GetShipViaCodes2Response.php',
        'Visual\CustomerService\ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'Visual\CustomerService\GetDefaultCustomerShipViaCode2' => __DIR__ .'/GetDefaultCustomerShipViaCode2.php',
        'Visual\CustomerService\GetDefaultCustomerShipViaCode2Response' => __DIR__ .'/GetDefaultCustomerShipViaCode2Response.php',
        'Visual\CustomerService\GetDefaultCustomerShipViaCode' => __DIR__ .'/GetDefaultCustomerShipViaCode.php',
        'Visual\CustomerService\GetDefaultCustomerShipViaCodeResponse' => __DIR__ .'/GetDefaultCustomerShipViaCodeResponse.php',
        'Visual\CustomerService\Header' => __DIR__ .'/Header.php',
        'Visual\CustomerService\GetShipViaCodes' => __DIR__ .'/GetShipViaCodes.php',
        'Visual\CustomerService\GetShipViaCodesResponse' => __DIR__ .'/GetShipViaCodesResponse.php',
        'Visual\CustomerService\PurchaseOrderIDExists' => __DIR__ .'/PurchaseOrderIDExists.php',
        'Visual\CustomerService\PurchaseOrderIDExistsResponse' => __DIR__ .'/PurchaseOrderIDExistsResponse.php',
        'Visual\CustomerService\PurchaseOrderIDExists2' => __DIR__ .'/PurchaseOrderIDExists2.php',
        'Visual\CustomerService\PurchaseOrderIDExists2Response' => __DIR__ .'/PurchaseOrderIDExists2Response.php',
        'Visual\CustomerService\CreatePhoneCustomer2' => __DIR__ .'/CreatePhoneCustomer2.php',
        'Visual\CustomerService\CreatePhoneCustomer2Response' => __DIR__ .'/CreatePhoneCustomer2Response.php',
        'Visual\CustomerService\CreateCustomer2' => __DIR__ .'/CreateCustomer2.php',
        'Visual\CustomerService\CreateCustomer2Response' => __DIR__ .'/CreateCustomer2Response.php',
        'Visual\CustomerService\TestLoadCustomerDataByShipTO' => __DIR__ .'/TestLoadCustomerDataByShipTO.php',
        'Visual\CustomerService\TestLoadCustomerDataByShipTOResponse' => __DIR__ .'/TestLoadCustomerDataByShipTOResponse.php',
        'Visual\CustomerService\LoadCustomerDataByShipTO2' => __DIR__ .'/LoadCustomerDataByShipTO2.php',
        'Visual\CustomerService\LoadCustomerDataByShipTO2Response' => __DIR__ .'/LoadCustomerDataByShipTO2Response.php',
        'Visual\CustomerService\LoadCustomerDataByShipTOUserDefined12' => __DIR__ .'/LoadCustomerDataByShipTOUserDefined12.php',
        'Visual\CustomerService\LoadCustomerDataByShipTOUserDefined12Response' => __DIR__ .'/LoadCustomerDataByShipTOUserDefined12Response.php',
        'Visual\CustomerService\LoadCustomerDataByOrderID2' => __DIR__ .'/LoadCustomerDataByOrderID2.php',
        'Visual\CustomerService\LoadCustomerDataByOrderID2Response' => __DIR__ .'/LoadCustomerDataByOrderID2Response.php',
        'Visual\CustomerService\LoadCustomerDataByWebID' => __DIR__ .'/LoadCustomerDataByWebID.php',
        'Visual\CustomerService\LoadCustomerDataByWebIDResponse' => __DIR__ .'/LoadCustomerDataByWebIDResponse.php',
        'Visual\CustomerService\LoadShipTOByAddress' => __DIR__ .'/LoadShipTOByAddress.php',
        'Visual\CustomerService\LoadShipTOByAddressResponse' => __DIR__ .'/LoadShipTOByAddressResponse.php',
        'Visual\CustomerService\TestLoadCustomerDataByOrderID' => __DIR__ .'/TestLoadCustomerDataByOrderID.php',
        'Visual\CustomerService\TestLoadCustomerDataByOrderIDResponse' => __DIR__ .'/TestLoadCustomerDataByOrderIDResponse.php',
        'Visual\CustomerService\LokupWarehouseByID' => __DIR__ .'/LokupWarehouseByID.php',
        'Visual\CustomerService\LokupWarehouseByIDResponse' => __DIR__ .'/LokupWarehouseByIDResponse.php',
        'Visual\CustomerService\LookupNameByID' => __DIR__ .'/LookupNameByID.php',
        'Visual\CustomerService\LookupNameByIDResponse' => __DIR__ .'/LookupNameByIDResponse.php',
        'Visual\CustomerService\LokupNameByID' => __DIR__ .'/LokupNameByID.php',
        'Visual\CustomerService\LokupNameByIDResponse' => __DIR__ .'/LokupNameByIDResponse.php',
        'Visual\CustomerService\LoadCustomerDataByOrderID' => __DIR__ .'/LoadCustomerDataByOrderID.php',
        'Visual\CustomerService\LoadCustomerDataByOrderIDResponse' => __DIR__ .'/LoadCustomerDataByOrderIDResponse.php',
        'Visual\CustomerService\LoadCustomerDataByShipTO' => __DIR__ .'/LoadCustomerDataByShipTO.php',
        'Visual\CustomerService\LoadCustomerDataByShipTOResponse' => __DIR__ .'/LoadCustomerDataByShipTOResponse.php',
        'Visual\CustomerService\LoadCustomerDataByShipTOUserDefined1' => __DIR__ .'/LoadCustomerDataByShipTOUserDefined1.php',
        'Visual\CustomerService\LoadCustomerDataByShipTOUserDefined1Response' => __DIR__ .'/LoadCustomerDataByShipTOUserDefined1Response.php',
        'Visual\CustomerService\CreateCustomer' => __DIR__ .'/CreateCustomer.php',
        'Visual\CustomerService\CreateCustomerResponse' => __DIR__ .'/CreateCustomerResponse.php',
        'Visual\CustomerService\SampleCustomer' => __DIR__ .'/SampleCustomer.php',
        'Visual\CustomerService\SampleCustomerResponse' => __DIR__ .'/SampleCustomerResponse.php',
        'Visual\CustomerService\SampleCustomerCD65' => __DIR__ .'/SampleCustomerCD65.php',
        'Visual\CustomerService\SampleCustomerCD65Response' => __DIR__ .'/SampleCustomerCD65Response.php',
        'Visual\CustomerService\TestSample' => __DIR__ .'/TestSample.php',
        'Visual\CustomerService\TestSampleResponse' => __DIR__ .'/TestSampleResponse.php',
        'Visual\CustomerService\TestUpdateCustomerAddress' => __DIR__ .'/TestUpdateCustomerAddress.php',
        'Visual\CustomerService\TestUpdateCustomerAddressResponse' => __DIR__ .'/TestUpdateCustomerAddressResponse.php',
        'Visual\CustomerService\AddNewAddress' => __DIR__ .'/AddNewAddress.php',
        'Visual\CustomerService\AddNewAddressResponse' => __DIR__ .'/AddNewAddressResponse.php',
        'Visual\CustomerService\SearchCustomer' => __DIR__ .'/SearchCustomer.php',
        'Visual\CustomerService\SearchCustomerResponse' => __DIR__ .'/SearchCustomerResponse.php',
        'Visual\CustomerService\SearchCustomerLike' => __DIR__ .'/SearchCustomerLike.php',
        'Visual\CustomerService\SearchCustomerLikeResponse' => __DIR__ .'/SearchCustomerLikeResponse.php',
        'Visual\CustomerService\TestSearchCustomer' => __DIR__ .'/TestSearchCustomer.php',
        'Visual\CustomerService\TestSearchCustomerResponse' => __DIR__ .'/TestSearchCustomerResponse.php',
        'Visual\CustomerService\SearchAddress' => __DIR__ .'/SearchAddress.php',
        'Visual\CustomerService\AddressData' => __DIR__ .'/AddressData.php',
        'Visual\CustomerService\SearchAddressResponse' => __DIR__ .'/SearchAddressResponse.php',
        'Visual\CustomerService\SearchAddressLike' => __DIR__ .'/SearchAddressLike.php',
        'Visual\CustomerService\SearchAddressLikeResponse' => __DIR__ .'/SearchAddressLikeResponse.php',
        'Visual\CustomerService\TestSearchAdderess' => __DIR__ .'/TestSearchAdderess.php',
        'Visual\CustomerService\TestSearchAdderessResponse' => __DIR__ .'/TestSearchAdderessResponse.php',
        'Visual\CustomerService\CurrentVersion' => __DIR__ .'/CurrentVersion.php',
        'Visual\CustomerService\CurrentVersionResponse' => __DIR__ .'/CurrentVersionResponse.php',
        'Visual\CustomerService\LoginCreds' => __DIR__ .'/LoginCreds.php',
        'Visual\CustomerService\LoginCredsResponse' => __DIR__ .'/LoginCredsResponse.php',
        'Visual\CustomerService\NextNumberGenAppenditure' => __DIR__ .'/NextNumberGenAppenditure.php',
        'Visual\CustomerService\NextNumberGenAppenditureResponse' => __DIR__ .'/NextNumberGenAppenditureResponse.php',
        'Visual\CustomerService\UserPermission' => __DIR__ .'/UserPermission.php',
        'Visual\CustomerService\UserPermissionResponse' => __DIR__ .'/UserPermissionResponse.php',
        'Visual\CustomerService\UserPermissionEnum' => __DIR__ .'/UserPermissionEnum.php',
        'Visual\CustomerService\NextNumberGen2' => __DIR__ .'/NextNumberGen2.php',
        'Visual\CustomerService\NextNumberGen2Response' => __DIR__ .'/NextNumberGen2Response.php',
        'Visual\CustomerService\InstallSchemaDatabaseLogMessage' => __DIR__ .'/InstallSchemaDatabaseLogMessage.php',
        'Visual\CustomerService\InstallSchemaDatabaseLogMessageResponse' => __DIR__ .'/InstallSchemaDatabaseLogMessageResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_7d104799db9f3474a7613fa25a772746');

// Do nothing. The rest is just leftovers from the code generation.
{
}
