<?php
/**
 * Created by PhpStorm.
 * User: magentouser
 * Date: 3/3/15
 * Time: 3:07 PM
 */
$incrementId = $this->getOrder()->getIncrementId();
$status = $this->getOrder()->getAeSentToVisual();
$attempts = $this->getOrder()->getAeVisualPushAttempt();
?>

<div id="order_visual_block">
	<h2>Order ID <?php echo $incrementId ?> has push status: <strong><?php echo $status == '1' ? 'SENT' : 'NOT SENT'; ?></strong></h2>

	<?php if($status == '1'): ?>
	<p>You may change the status to not sent, and the system will attempt to
	push the order to the VISUAL system, However if the order has already been
	accepted, the VISUAL system will report an exception.</p>
	<p><?php echo $this->getChildHtml('submit_clear_button') ?></p>
	<?php else: ?>
	<p>You may mark this order as already sent to prevent the system from making further
	attempts to push this order. You may need to do this if the order was transferred
	manually.</p>
	<p><?php echo $this->getChildHtml('submit_set_button') ?></p>
	<?php endif; ?>

</div>