<?php
/**
 * Created by PhpStorm.
 * User: mageuser
 * Date: 2/5/16
 * Time: 1:27 PM
 */

class Shelterlogic_Templates_Block_Requestquote extends Mage_Core_Block_Template {
    private $product = null;
    private $parent = null;
    /**
     * @return $this
     */
    protected function _prepareLayout() {
        $sku = $this->getRequest()->getParam('sku');
        if ($sku) {
            $this->product = Mage::getModel('catalog/product')->loadByAttribute('sku', $sku);
            $pid = Mage::getModel('catalog/product_type_configurable')->getParentIdsByChild($this->product->getId());
            $this->parent = Mage::getModel('catalog/product')->load(current($pid));
        }
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function getFormHtml() {
        return $this->getLayout()->createBlock('webforms/webforms', 'quote_webform_block', array(
            'webform_id' => 3,
            'template' => 'webforms/default.phtml',
        ))->toHtml();
    }
    public function getConfigAttributes() {
        $map = array();
        $atts = $this->parent->getTypeInstance(true)->getConfigurableAttributes($this->parent);
        /** @var Mage_Catalog_Model_Product_Type_Configurable_Attribute $att */
        foreach ($atts as $att) {
            $map[$att->getProductAttribute()->getFrontendLabel()] =
                $this->product
                    ->getResource()
                    ->getAttribute($att->getProductAttribute()
                        ->getAttributeCode())
                    ->getFrontend()
                    ->getValue($this->product);
        }

        return $map;
    }
    public function getProduct() {
        return $this->product;
    }
    public function getParent() {
        return $this->parent;
    }
    public function getModalHeader() {
        return $this->getLayout()->createBlock('cms/block')->setBlockId('quote-modal-header')->toHtml();
    }
    public function getFormattedPrice(){
        return '';
    }
}