<script type="text/javascript">
    (function($, undefined) {
        $(function() {
            $('.wishlist-toggle').on('click', function(e) {
                e.preventDefault();
                <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                    window.location.href = $(this).data('url');
                <?php else: ?>
                    $.ajax({
                        'url': '<?php echo Mage::getUrl('slwishlist/ajax/toggle') ?>',
                        'data': {'product': $(this).data('id')}
                    })
                        .done(function(response) {
                            switch (response.status) {
                                case 'error':
                                    window.location.reload();
                                    break;
                                case 'added':
                                    $(this).addClass('active');
                                    $(this).attr('title', 'Remove from wishlist');
                                    break;
                                case 'removed':
                                    $(this).removeClass('active');
                                    $(this).attr('title', 'Add to wishlist');
                                    break;
                            }
                        }.bind(this));
                <?php endif; ?>
            });

            <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                var wishlistProductIds = <?php echo $this->getWishlistProductsJson() ?>;
                $.each(wishlistProductIds, function(index, value) {
                    $('#wishlist-toggle-' + value).addClass('active');
                    $('#wishlist-toggle-' + value).attr('title', 'Remove from wishlist');
                });
            <?php endif; ?>
        });
    })(jQuery);
</script>