<?php


 function autoload_4a5b9dea23d04cd4dcb5aa04d01913e5($class)
{
    $classes = array(
        'Visual\InventoryService\InventoryService' => __DIR__ .'/InventoryService.php',
        'Visual\InventoryService\TracePartLocations2' => __DIR__ .'/TracePartLocations2.php',
        'Visual\InventoryService\TracePartLocations2Response' => __DIR__ .'/TracePartLocations2Response.php',
        'Visual\InventoryService\ArrayOfInventoryRequisitionTrace' => __DIR__ .'/ArrayOfInventoryRequisitionTrace.php',
        'Visual\InventoryService\InventoryRequisitionTrace' => __DIR__ .'/InventoryRequisitionTrace.php',
        'Visual\InventoryService\TraceLocation' => __DIR__ .'/TraceLocation.php',
        'Visual\InventoryService\TracePartLocations' => __DIR__ .'/TracePartLocations.php',
        'Visual\InventoryService\TracePartLocationsResponse' => __DIR__ .'/TracePartLocationsResponse.php',
        'Visual\InventoryService\Header' => __DIR__ .'/Header.php',
        'Visual\InventoryService\TraceIDExists' => __DIR__ .'/TraceIDExists.php',
        'Visual\InventoryService\TraceIDExistsResponse' => __DIR__ .'/TraceIDExistsResponse.php',
        'Visual\InventoryService\ServiceChargeExists' => __DIR__ .'/ServiceChargeExists.php',
        'Visual\InventoryService\ServiceChargeExistsResponse' => __DIR__ .'/ServiceChargeExistsResponse.php',
        'Visual\InventoryService\TraceProfileExists' => __DIR__ .'/TraceProfileExists.php',
        'Visual\InventoryService\TraceProfileExistsResponse' => __DIR__ .'/TraceProfileExistsResponse.php',
        'Visual\InventoryService\PartIDExists' => __DIR__ .'/PartIDExists.php',
        'Visual\InventoryService\PartIDExistsResponse' => __DIR__ .'/PartIDExistsResponse.php',
        'Visual\InventoryService\PartLocationExists' => __DIR__ .'/PartLocationExists.php',
        'Visual\InventoryService\PartLocationExistsResponse' => __DIR__ .'/PartLocationExistsResponse.php',
        'Visual\InventoryService\PartWarehouseExists' => __DIR__ .'/PartWarehouseExists.php',
        'Visual\InventoryService\PartWarehouseExistsResponse' => __DIR__ .'/PartWarehouseExistsResponse.php',
        'Visual\InventoryService\WarehouseExists' => __DIR__ .'/WarehouseExists.php',
        'Visual\InventoryService\WarehouseExistsResponse' => __DIR__ .'/WarehouseExistsResponse.php',
        'Visual\InventoryService\LocationExists' => __DIR__ .'/LocationExists.php',
        'Visual\InventoryService\LocationExistsResponse' => __DIR__ .'/LocationExistsResponse.php',
        'Visual\InventoryService\GetPartBySKU' => __DIR__ .'/GetPartBySKU.php',
        'Visual\InventoryService\GetPartBySKUResponse' => __DIR__ .'/GetPartBySKUResponse.php',
        'Visual\InventoryService\GetMaterialCost' => __DIR__ .'/GetMaterialCost.php',
        'Visual\InventoryService\GetMaterialCostResponse' => __DIR__ .'/GetMaterialCostResponse.php',
        'Visual\InventoryService\GetInventoryPosition' => __DIR__ .'/GetInventoryPosition.php',
        'Visual\InventoryService\GetInventoryPositionResponse' => __DIR__ .'/GetInventoryPositionResponse.php',
        'Visual\InventoryService\LookupUnitPrice2' => __DIR__ .'/LookupUnitPrice2.php',
        'Visual\InventoryService\LookupUnitPrice2Response' => __DIR__ .'/LookupUnitPrice2Response.php',
        'Visual\InventoryService\PartPriceResponse' => __DIR__ .'/PartPriceResponse.php',
        'Visual\InventoryService\PartPriceRequest' => __DIR__ .'/PartPriceRequest.php',
        'Visual\InventoryService\LookupUnitPrice' => __DIR__ .'/LookupUnitPrice.php',
        'Visual\InventoryService\LookupUnitPriceResponse' => __DIR__ .'/LookupUnitPriceResponse.php',
        'Visual\InventoryService\LookupUnitPriceByVisualRules' => __DIR__ .'/LookupUnitPriceByVisualRules.php',
        'Visual\InventoryService\LookupUnitPriceByVisualRulesResponse' => __DIR__ .'/LookupUnitPriceByVisualRulesResponse.php',
        'Visual\InventoryService\TestLookupUnitPrice' => __DIR__ .'/TestLookupUnitPrice.php',
        'Visual\InventoryService\TestLookupUnitPriceResponse' => __DIR__ .'/TestLookupUnitPriceResponse.php',
        'Visual\InventoryService\TestInventoryTransfer' => __DIR__ .'/TestInventoryTransfer.php',
        'Visual\InventoryService\TestInventoryTransferResponse' => __DIR__ .'/TestInventoryTransferResponse.php',
        'Visual\InventoryService\ProcessInventoryTransaction2' => __DIR__ .'/ProcessInventoryTransaction2.php',
        'Visual\InventoryService\InventoryTransactionData' => __DIR__ .'/InventoryTransactionData.php',
        'Visual\InventoryService\ArrayOfInventoryTransfer' => __DIR__ .'/ArrayOfInventoryTransfer.php',
        'Visual\InventoryService\InventoryTransfer' => __DIR__ .'/InventoryTransfer.php',
        'Visual\InventoryService\ArrayOfInventoryAdjustIN' => __DIR__ .'/ArrayOfInventoryAdjustIN.php',
        'Visual\InventoryService\InventoryAdjustIN' => __DIR__ .'/InventoryAdjustIN.php',
        'Visual\InventoryService\ArrayOfInventoryAdjustOUT' => __DIR__ .'/ArrayOfInventoryAdjustOUT.php',
        'Visual\InventoryService\InventoryAdjustOUT' => __DIR__ .'/InventoryAdjustOUT.php',
        'Visual\InventoryService\ArrayOfInventoryMaterialIssue' => __DIR__ .'/ArrayOfInventoryMaterialIssue.php',
        'Visual\InventoryService\InventoryMaterialIssue' => __DIR__ .'/InventoryMaterialIssue.php',
        'Visual\InventoryService\ArrayOfInventoryWOReceipt' => __DIR__ .'/ArrayOfInventoryWOReceipt.php',
        'Visual\InventoryService\InventoryWOReceipt' => __DIR__ .'/InventoryWOReceipt.php',
        'Visual\InventoryService\ProcessInventoryTransaction2Response' => __DIR__ .'/ProcessInventoryTransaction2Response.php',
        'Visual\InventoryService\ProcessInventoryTransaction' => __DIR__ .'/ProcessInventoryTransaction.php',
        'Visual\InventoryService\ProcessInventoryTransactionResponse' => __DIR__ .'/ProcessInventoryTransactionResponse.php',
        'Visual\InventoryService\ProcessPhisicalInventoryTransaction2' => __DIR__ .'/ProcessPhisicalInventoryTransaction2.php',
        'Visual\InventoryService\InventoryCycleCountData' => __DIR__ .'/InventoryCycleCountData.php',
        'Visual\InventoryService\ArrayOfInventoryCycleCount' => __DIR__ .'/ArrayOfInventoryCycleCount.php',
        'Visual\InventoryService\InventoryCycleCount' => __DIR__ .'/InventoryCycleCount.php',
        'Visual\InventoryService\ProcessPhisicalInventoryTransaction2Response' => __DIR__ .'/ProcessPhisicalInventoryTransaction2Response.php',
        'Visual\InventoryService\ProcessPhisicalInventoryTransaction' => __DIR__ .'/ProcessPhisicalInventoryTransaction.php',
        'Visual\InventoryService\ProcessPhisicalInventoryTransactionResponse' => __DIR__ .'/ProcessPhisicalInventoryTransactionResponse.php',
        'Visual\InventoryService\TestGetPartList' => __DIR__ .'/TestGetPartList.php',
        'Visual\InventoryService\TestGetPartListResponse' => __DIR__ .'/TestGetPartListResponse.php',
        'Visual\InventoryService\PartDataResponse' => __DIR__ .'/PartDataResponse.php',
        'Visual\InventoryService\BaseDataResponse' => __DIR__ .'/BaseDataResponse.php',
        'Visual\InventoryService\ArrayOfPartListItem' => __DIR__ .'/ArrayOfPartListItem.php',
        'Visual\InventoryService\PartListItem' => __DIR__ .'/PartListItem.php',
        'Visual\InventoryService\Part' => __DIR__ .'/Part.php',
        'Visual\InventoryService\GetPartList' => __DIR__ .'/GetPartList.php',
        'Visual\InventoryService\GetPartListResponse' => __DIR__ .'/GetPartListResponse.php',
        'Visual\InventoryService\CurrentVersion' => __DIR__ .'/CurrentVersion.php',
        'Visual\InventoryService\CurrentVersionResponse' => __DIR__ .'/CurrentVersionResponse.php',
        'Visual\InventoryService\LoginCreds' => __DIR__ .'/LoginCreds.php',
        'Visual\InventoryService\LoginCredsResponse' => __DIR__ .'/LoginCredsResponse.php',
        'Visual\InventoryService\NextNumberGenAppenditure' => __DIR__ .'/NextNumberGenAppenditure.php',
        'Visual\InventoryService\NextNumberGenAppenditureResponse' => __DIR__ .'/NextNumberGenAppenditureResponse.php',
        'Visual\InventoryService\UserPermission' => __DIR__ .'/UserPermission.php',
        'Visual\InventoryService\UserPermissionResponse' => __DIR__ .'/UserPermissionResponse.php',
        'Visual\InventoryService\UserPermissionEnum' => __DIR__ .'/UserPermissionEnum.php',
        'Visual\InventoryService\NextNumberGen2' => __DIR__ .'/NextNumberGen2.php',
        'Visual\InventoryService\NextNumberGen2Response' => __DIR__ .'/NextNumberGen2Response.php',
        'Visual\InventoryService\InstallSchemaDatabaseLogMessage' => __DIR__ .'/InstallSchemaDatabaseLogMessage.php',
        'Visual\InventoryService\InstallSchemaDatabaseLogMessageResponse' => __DIR__ .'/InstallSchemaDatabaseLogMessageResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_4a5b9dea23d04cd4dcb5aa04d01913e5', true, true);

// Do nothing. The rest is just leftovers from the code generation.
{
}
