<!----------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------

HTML TEMPLATE: BEGIN

------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------>

<div class="page-title category-title">
        <h2>Featured Product</h2>
</div>

	<div class="category-products">

		<ul class="products-grid products-grid--max-3-col">

			<li class="item wish-active">
				<a href="/products/anchors/shelterauger-15-earth-anchors" title="ShelterAuger 15&quot; Earth Anchors">
					<img id="product-collection-image-41353" src="/media/catalog/product/cache/7/small_image/260x260/9df78eab33525d08d6e5fb8d27136e95/1/0/10073_600x600_01_3_1_1_1_1_1_1.jpg" alt="ShelterAuger 15&quot; Earth Anchors" />
					<div class="product-info clearfix">
						<div class="product-west">
							<h3 class="product-name">ShelterAuger 15&quot; Earth Anchors</h3>
							<div class="product-category">Top Level Category</div>
						</div>
						<div class="product-east">
							<div class="price-box">
								<span class="regular-price" id="product-price-41353">
									<span class="price">$19.99</span>
								</span>
							</div>
							<button type="button" title="Add to Cart" class="button btn-cart"><span><span>Add to Cart</span></span></button>
						</div>
					</div>
				</a>
			</li>

			<li class="item">
				<a href="/products/anchors/shelterauger-15-earth-anchors" title="ShelterAuger 15&quot; Earth Anchors">
					<img id="product-collection-image-41353" src="/media/catalog/product/cache/7/small_image/260x260/9df78eab33525d08d6e5fb8d27136e95/1/0/10073_600x600_01_3_1_1_1_1_1_1.jpg" alt="ShelterAuger 15&quot; Earth Anchors" />
					<div class="product-info clearfix">
						<div class="product-west">
							<h3 class="product-name">ShelterAuger 15&quot; Earth Anchors</h3>
							<div class="product-category">Top Level Category</div>
						</div>
						<div class="product-east">
							<div class="price-box">
								<span class="regular-price" id="product-price-41353">
									<span class="price">$19.99</span>
								</span>
							</div>
							<button type="button" title="Add to Cart" class="button btn-cart"><span><span>Add to Cart</span></span></button>
						</div>
					</div>
				</a>
			</li>

			<li class="item">
				<a class="onsale" href="/products/anchors/shelterauger-15-earth-anchors" title="ShelterAuger 15&quot; Earth Anchors">
					<img id="product-collection-image-41353" src="/media/catalog/product/cache/7/small_image/260x260/9df78eab33525d08d6e5fb8d27136e95/1/0/10073_600x600_01_3_1_1_1_1_1_1.jpg" alt="ShelterAuger 15&quot; Earth Anchors" />
					<div class="product-info clearfix">
						<div class="product-west">
							<h3 class="product-name">ShelterAuger 15&quot; Earth Anchors</h3>
							<div class="product-category">Top Level Category</div>
						</div>
						<div class="product-east">
							<div class="price-box">
								<span class="regular-price" id="product-price-41353">
									<span class="price">$19.99</span>
								</span>
							</div>
							<button type="button" title="Add to Cart" class="button btn-cart"><span><span>Add to Cart</span></span></button>
						</div>
					</div>
				</a>
			</li>

			<li class="item">
				<a href="/products/anchors/shelterauger-15-earth-anchors" title="ShelterAuger 15&quot; Earth Anchors">
					<img id="product-collection-image-41353" src="/media/catalog/product/cache/7/small_image/260x260/9df78eab33525d08d6e5fb8d27136e95/1/0/10073_600x600_01_3_1_1_1_1_1_1.jpg" alt="ShelterAuger 15&quot; Earth Anchors" />
					<div class="product-info clearfix">
						<div class="product-west">
							<h3 class="product-name">ShelterAuger 15&quot; Earth Anchors</h3>
							<div class="product-category">Top Level Category</div>
						</div>
						<div class="product-east">
							<div class="price-box">
								<span class="regular-price" id="product-price-41353">
									<span class="price">$19.99</span>
								</span>
							</div>
							<button type="button" title="Add to Cart" class="button btn-cart"><span><span>Add to Cart</span></span></button>
						</div>
					</div>
				</a>
			</li>

			<li class="item">
				<a href="/products/anchors/shelterauger-15-earth-anchors" title="ShelterAuger 15&quot; Earth Anchors">
					<img id="product-collection-image-41353" src="/media/catalog/product/cache/7/small_image/260x260/9df78eab33525d08d6e5fb8d27136e95/1/0/10073_600x600_01_3_1_1_1_1_1_1.jpg" alt="ShelterAuger 15&quot; Earth Anchors" />
					<div class="product-info clearfix">
						<div class="product-west">
							<h3 class="product-name">ShelterAuger 15&quot; Earth Anchors</h3>
							<div class="product-category">Top Level Category</div>
						</div>
						<div class="product-east">
							<div class="price-box">
								<span class="regular-price" id="product-price-41353">
									<span class="price">$19.99</span>
								</span>
							</div>
							<button type="button" title="Add to Cart" class="button btn-cart"><span><span>Add to Cart</span></span></button>
						</div>
					</div>
				</a>
			</li>

			<li class="item">
				<a href="/products/anchors/shelterauger-15-earth-anchors" title="ShelterAuger 15&quot; Earth Anchors">
					<img id="product-collection-image-41353" src="/media/catalog/product/cache/7/small_image/260x260/9df78eab33525d08d6e5fb8d27136e95/1/0/10073_600x600_01_3_1_1_1_1_1_1.jpg" alt="ShelterAuger 15&quot; Earth Anchors" />
					<div class="product-info clearfix">
						<div class="product-west">
							<h3 class="product-name">ShelterAuger 15&quot; Earth Anchors</h3>
							<div class="product-category">Top Level Category</div>
						</div>
						<div class="product-east">
							<div class="price-box">
								<span class="regular-price" id="product-price-41353">
									<span class="price">$19.99</span>
								</span>
							</div>
							<button type="button" title="Add to Cart" class="button btn-cart"><span><span>Add to Cart</span></span></button>
						</div>
					</div>
				</a>
			</li>

		</ul>

	</div>




<div class="page-title category-title">
        <h2>Sub Categories</h2>
</div>


	<div class="category-products sub-categories">

		<ul class="products-grid products-grid--max-3-col">

			<li class="item">
				<a href="/products/anchors/shelterauger-15-earth-anchors" title="ShelterAuger 15&quot; Earth Anchors">
					<img id="product-collection-image-41353" src="/templates/images/sub-categories.gif" alt="ShelterAuger 15&quot; Earth Anchors" />
					<h4 class="product-name">Sub Categories</h4>
				</a>
			</li>

			<li class="item">
				<a href="/products/anchors/shelterauger-15-earth-anchors" title="ShelterAuger 15&quot; Earth Anchors">
					<img id="product-collection-image-41353" src="/templates/images/sub-categories.gif" alt="ShelterAuger 15&quot; Earth Anchors" />
					<h4 class="product-name">Sub Categories</h4>
				</a>
			</li>

			<li class="item">
				<a href="/products/anchors/shelterauger-15-earth-anchors" title="ShelterAuger 15&quot; Earth Anchors">
					<img id="product-collection-image-41353" src="/templates/images/sub-categories.gif" alt="ShelterAuger 15&quot; Earth Anchors" />
					<h4 class="product-name">Sub Categories</h4>
				</a>
			</li>

		</ul>

	</div>




<!----------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------

HTML TEMPLATE: END

------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------>