<div class="department-listing-all">
    <!--
    <div class="department-listing-image"><img src="/skin/frontend/allanjcoleman/default/images/department_listing-banner.jpg" alt="Diagnostics/Locating" />
        <div class="department-listing-image-content">
            <div class="department-listing-image-text">
                <h3>Industry Standard</h3>
                <p>RIDGID<sup>&reg;</sup> SeeSnake<sup>&reg;</sup> and SeekTech<sup>&reg;</sup> diagnostics, inspection and locating tools are the industry standard for ruggedness, pushability and ease of use.</p>
            </div>
        </div>
    </div>
    -->

    <div class="category-products">
        <ul class="products-grid">
            <?php
            /** @var Mage_Catalog_Block_Navigation $this */
            //$_categories=$this->getCurrentChildCategories();
            $collection = Mage::getModel('catalog/category')->getCollection();
            $current_category = Mage::getModel('catalog/layer')->getCurrentCategory();
            $collection->addAttributeToSelect('url_key')
                ->addAttributeToSelect('name')
                ->addAttributeToSelect('is_anchor')
                ->addAttributeToSelect('image')
                ->addAttributeToFilter('is_active', 1)
//                ->addIdFilter($this->getCurrentCategory()->getChildren())
                ->addIdFilter($current_category->getChildren())
                ->setOrder('position', 'ASC')
                ->joinUrlRewrite()
                ->load();

            if($collection->count()):
                $categorycount = 0;
                foreach ($collection as $_category):

                    if($_category->getIsActive()):
                        $cur_category=Mage::getModel('catalog/category')->load($_category->getId());

                        $layer = Mage::getSingleton('catalog/layer');
                        $layer->setCurrentCategory($cur_category);
                        $catName = $current_category->getName();
                        if ($categorycount == 0){
                            $class = "first";
                        }
                        elseif ($categorycount == 3){
                            $class = "last";
                        }
                        else{
                            $class = "";
                        }
                        ?>
                        <li class="item <?=$class?>">
                            <a href="<?php echo $_category->getURL() ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>">
                                <div class="dept-list-image"><div class="dept-list-image-in"><img src="<?php echo $_category->getImageUrl() ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" /></div></div>
                                <div class="dept-list-cmla">
                                    <div class="dept-list-value">
                                        <div class="mod">
                                            $37.99
                                        </div>
                                    </div>
                                    <div class="dept-list-name">
                                        <div class="mod">
                                            <h2><?php echo $this->htmlEscape($_category->getName()) ?></h2>
                                            <div class="tlc">Top Level Category</div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                    <?php
                    endif;
                    if($categorycount == 3){
                        $categorycount = 0;
                        echo "</ul>\n\n<ul class=\"products-grid\">";
                    }
                    else{
                        $categorycount++;
                    }
                endforeach;
            endif;
            ?>
        </ul>
        </div>
</div>