<?php
/**
 * Created by PhpStorm.
 * User: mageuser
 * Date: 10/6/16
 * Time: 12:43 PM
 */



class Americaneagle_SchedulerExtensions_Block_Adminhtml_Stuckjobs
    extends Mage_Adminhtml_Block_Widget_Grid_Container
{
    public function __construct()
    {
        $this->_blockGroup = 'americaneagle_schedulerExtensions';
        $this->_controller = 'adminhtml_stuckjobs';
        $this->_headerText = $this->__('Running Tasks');
        parent::__construct();
    }

    /**
     * @return Mage_Core_Block_Abstract
     */
    protected function _prepareLayout()
    {
        $this->removeButton('add');
        if($this->schedulerDirExists()) {
            $this->_addButton(
                'remove_tmp_dir',
                array(
                    'label' => 'Remove Scheduler Lock Directories',
                    'onclick' => "setLocation('{$this->getUrl('*/*/removeLock')}')"
                )
            );
        } else {
            $this->_addButton(
                'remove_tmp_dir', array(
                    'label' => 'No Lock Directories present',
                    'class' => 'disabled'
                    )
            );
        }
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
    private function schedulerDirExists() {
        $files = scandir('/tmp');
        foreach ($files as $file) {
            if(0 === strpos($file, 'magento.aoe_scheduler')){
                return true;
            }
        }

        return false;
    }
}