<?php
/**
 * Created by PhpStorm.
 * User: magentouser
 * Date: 12/5/14
 * Time: 3:18 PM
 */

class Americaneagle_Visual_Block_Adminhtml_Soaplog_View extends Mage_Adminhtml_Block_Widget_Container {
	private $helper;
	private $row;

	public function __construct(array $args = array()) {
		$this->helper = Mage::helper('americaneagle_visual');
		parent::__construct($args); // TODO: Change the autogenerated stub

	}

	public function getHeaderText() {
		return $this->__('Soap Log View');
	}


	protected function _prepareLayout() {
		$this->_addButton('back', array(
			'label'   => $this->helper->__('Back'),
			'onclick' => "setLocation('" . $this->getUrl('*/*/') . "')",
			'class'   => 'back'
		));

		return parent::_prepareLayout(); // TODO: Change the autogenerated stub
	}

	public function getSoapLogRow() {
		if(empty($this->row)){
			$this->row = Mage::getModel('americaneagle_visual/Soaplog')->load($this->getRequest()->getParam('soaplog_id'));
		}
		return $this->row;
	}
} 